FROM python:3.9-slim

WORKDIR /app

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY python/ .
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/google_auth.json

CMD ["python3", "main.py", "friend"]